import { NextRequest, NextResponse } from 'next/server'

interface ContactRequest {
  propertyAddress: string
  listingUrl?: string
  realtorName?: string
  realtorPhone?: string
  realtorEmail?: string
  missingFields: string[]
  investorName?: string
  investorEmail?: string
  investorPhone?: string
}

// Field display names for professional inquiries
const fieldDisplayNames: Record<string, string> = {
  askingPrice: 'asking price',
  bedrooms: 'number of bedrooms',
  bathrooms: 'number of bathrooms',
  squareFeet: 'property size in square feet',
  tenure: 'tenure type (freehold/leasehold)',
  epcRating: 'EPC rating',
  yearBuilt: 'year the property was built',
  councilTaxBand: 'council tax band',
  propertyType: 'property type',
  address: 'full property address',
}

export async function POST(request: NextRequest) {
  try {
    const body: ContactRequest = await request.json()
    
    const {
      propertyAddress,
      listingUrl,
      realtorName,
      missingFields,
      investorName = 'DealPilot AI User',
      investorEmail,
      investorPhone,
    } = body

    // Generate a professional inquiry message
    const missingFieldsText = missingFields
      .map(field => fieldDisplayNames[field] || field)
      .join(', ')

    const inquiryMessage = generateInquiryMessage({
      propertyAddress,
      listingUrl,
      realtorName,
      missingFieldsText,
      investorName,
      investorEmail,
      investorPhone,
    })

    // In a real implementation, this would:
    // 1. Send an email via SendGrid/Resend
    // 2. Make an automated call via Twilio
    // 3. Submit a form on the listing portal
    // 4. Use an AI agent to navigate the realtor's website

    // For demo, simulate the AI agent workflow
    const agentSteps = [
      { step: 'Analyzing realtor contact information...', delay: 500 },
      { step: 'Preparing professional inquiry...', delay: 800 },
      { step: 'Identifying optimal contact method...', delay: 600 },
      { step: realtorName ? `Reaching out to ${realtorName}...` : 'Submitting inquiry to listing agent...', delay: 1000 },
      { step: 'Inquiry sent successfully', delay: 300 },
    ]

    // Return the inquiry details and simulated response
    return NextResponse.json({
      success: true,
      inquiry: {
        propertyAddress,
        missingFields,
        status: 'sent',
        message: inquiryMessage,
        timestamp: new Date().toISOString(),
        estimatedResponse: '24-48 hours',
        contactMethod: realtorName ? 'direct_agent' : 'listing_portal',
        agentWorkflow: agentSteps.map(s => s.step),
      },
      // Simulated pending response
      pendingResponse: {
        status: 'awaiting_response',
        expectedBy: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      },
    })

  } catch (error) {
    console.error('Contact realtor error:', error)
    return NextResponse.json(
      { error: 'Failed to contact realtor' },
      { status: 500 }
    )
  }
}

function generateInquiryMessage({
  propertyAddress,
  listingUrl,
  realtorName,
  missingFieldsText,
  investorName,
  investorEmail,
  investorPhone,
}: {
  propertyAddress: string
  listingUrl?: string
  realtorName?: string
  missingFieldsText: string
  investorName: string
  investorEmail?: string
  investorPhone?: string
}): string {
  const greeting = realtorName ? `Dear ${realtorName}` : 'Dear Sir/Madam'
  
  return `${greeting},

I am writing to express my interest in the property at ${propertyAddress}${listingUrl ? ` (${listingUrl})` : ''}.

As part of my investment analysis, I would greatly appreciate if you could provide the following additional details about this property:

${missingFieldsText.split(', ').map(field => `• ${field.charAt(0).toUpperCase() + field.slice(1)}`).join('\n')}

This information would help me complete my due diligence and move forward with a potential offer.

I would also welcome the opportunity to arrange a viewing at your earliest convenience.

Best regards,
${investorName}
${investorEmail ? `Email: ${investorEmail}` : ''}
${investorPhone ? `Phone: ${investorPhone}` : ''}

---
This inquiry was generated by DealPilot AI on behalf of the investor.`
}
